### ISSUE TITLE
Custom return path removes /

### ISSUE THREAD

**Issue by dustbro** [pabloveintimilla/mautic-amazon-ses#1]
I'm trying to set the custom return path. 
If I enter:
`URL_MAUTIC/mailer/callback`
it changes to this after I save:
`URL_MAUTICmailercallback`

I'm unable to send email until I clear this field.

**Comment by pabloveintimilla** [comment]
Hi,

I dont understand the issue, can you explain? 
Where you change the return path?

Regards!

**Comment by pabloveintimilla** [comment]
This issue is closed because not have enough information.
