### ISSUE TITLE
Plugin Installed but Schema ses+api Not Recognized in Mautic 5.x

### ISSUE THREAD

**Issue by costaeder** [pabloveintimilla/mautic-amazon-ses#11]
I installed the mautic-amazon-ses this plugin to enable Amazon SES integration in Mautic 5.1.1 running in Docker (mautic:5.1.1-apache). After installing the plugin, the ses+api schema was still not recognized, and I had to configure the SES transport directly in the local.php configuration file. Despite this, email sending fails with the following error:

 
```
Unknown DSN scheme. Please make sure the mailer DSN is configured properly.

```
Steps to Reproduce:
 
Actual Behavior: An error is thrown indicating that the ses+api schema is not recognized.

Environment Details:

Mautic Version: 5.1.1

Request for Assistance:

Is this plugin fully compatible with Mautic 5.1.1 Docker images (mautic:5.1.1-apache)?
Are there additional steps required to register the ses+api schema?
If there are known issues with this version of Mautic, is there a workaround or an upcoming fix?

**Comment by ZenDevMaster** [comment]
This worked for me:

`composer require pabloveintimilla/mautic-amazon-ses`
`php bin/console cache:clear`
`php bin/console mautic:plugins:reload`

Resolve any permissions issues or other errors with the above (if any).

Then, inside the Mautic admin:

Gear Icon -> Integrations -> Plugins

![image](https://github.com/user-attachments/assets/45422251-ed0b-4280-9fa8-7e712bb8eb66)

Click on "Install/Upgrade Plugins" in the top right corner

The AmazonSESBundle icon should appear in your list:
![image](https://github.com/user-attachments/assets/9fbd6174-120c-49a2-bb9d-ede0418dc3c4)

Now you're installed!



Now you should be able to create your EMail DSN with the scheme: **
![image](https://github.com/user-attachments/assets/01222431-5666-478a-9d97-4dd3241bceb6)

**Comment by pabloveintimilla** [comment]
Thanks @ZenDevMaster for your reply
