### ISSUE TITLE
Mautic 5.1.0

### ISSUE THREAD

**Issue by roberto-tenil** [pabloveintimilla/mautic-amazon-ses#2]
Nice plugin, but it's not working in Mautic 5.1.0.
Can you give a look?
Thank you.

**Comment by pabloveintimilla** [comment]
Hi, 

Can you detail the error or some screenshot.

Thanks!

**Comment by brunopastorellorocktrade** [comment]
Hello,

I am experiencing an invalid DNS error. Do you know why this might be happening? I will send an image to see if perhaps there is an issue with incorrect input.
![image](https://github.com/pabloveintimilla/mautic-amazon-ses/assets/78116490/011c0619-4017-4d63-b370-56dd8b4186d7)

**Comment by pabloveintimilla** [comment]
Check if plugin is enabled. 
![Mautic](https://github.com/pabloveintimilla/mautic-amazon-ses/assets/31135/3c92fe11-51a9-419f-8019-28ef99fb28a7)

I confirm that plugin work in Mautic 5.1

**Comment by roberto-tenil** [comment]
> Hi,
> 
> Can you detail the error or some screenshot.
> 
> Thanks!

![image](https://github.com/user-attachments/assets/c5bb22b2-62d3-42c2-b329-91b28a87f1de)

> Unable to send an email: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (code InvalidSignatureException).

I have already checked the credentials... they are correct and with full access to both SES and SNS.

Do you have any other thoughts on what the problem could be?

Thank you very much.

**Comment by brunopastorellorocktrade** [comment]
@roberto-tenil , eu estava enfrentando esse mesmo problema até ontem. A questão é que a chave acaba sendo armazenada incorretamente nas configurações locais. Não tenho certeza se é causado pelo plugin ou pelo próprio Mautic. O que fiz foi inserir manualmente a chave diretamente no arquivo de configuração. Se você verificar, verá que a chave está diferente do esperado. Isso causa problemas, pois ao enviar para o AWS, a string incorreta é enviada.

**Comment by roberto-tenil** [comment]
@brunopastorellorocktrade É exatamente isso que está acontecendo.

Chave armazenada incorretamente no arquivo `config/local.php`. Coloquei a chave manualmente e funcionou na hora.

Obrigado pela ajuda.

---

This is exactly what is happening.

Key stored incorrectly in `config/local.php` file. I entered the key manually and it worked right away.

Thanks for your help.
