### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by apitts** [pabloveintimilla/mautic-amazon-ses#9]
Is there a simple way to rate limit emails sent via the plugin? AWS SES of course enforces a max sends per second and I want to make sure that I don't exceed that limit. 

Adding a queue in Mautic 5 does not look that straightforward...I'm wondering if there is a simpler way and whether others have encountered this issue or did you find that Mautic 5 does not send that fast with this plugin on a relatively small server?

**Comment by pabloveintimilla** [comment]
Hi,

You can use limits options in cron jobs, check: https://docs.mautic.org/en/5.x/configuration/cron_jobs.html
